version: '3'

services:

  redis:
    image: redis

  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - "8082:8082"
    command: "gunicorn --workers=2 --bind=0.0.0.0:8082 movierecommender.wsgi:application"
    volumes:
      - ./src:/home/movierecommender/src/
      - ./docker/etc:/home/movierecommender/etc/
      - ./docker/etc/supervisor/api.conf:/etc/supervisor/conf.d/api.conf
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-movierecommender.settings}
    links:
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker.dockerfile
    volumes:
      - ./src:/home/movierecommender/src/
      - ./docker/etc:/home/movierecommender/etc/
      - ./docker/etc/supervisor/worker.conf:/etc/supervisor/conf.d/worker.conf
    command: bash -c "supervisord -n"
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE:-movierecommender.settings}
    links:
      - redis